### ISSUE TITLE
mkdocs instructions don't work as written

### ISSUE THREAD

**Issue by CapnKernel** [inventree/InvenTree#10995]
### Body of the issue

I'd like to run mkdocs locally so I can render the installation instructions that I'm editing.  I'm following the instructions here:

https://github.com/inventree/InvenTree/blob/master/docs/README.md

There is a minor problem that the instructions don't create a virtual environment.  That's fixable, but not what this issue is about.  The main problem is that these instructions require some things to be present in the local git repo that don't exist if the repo has just been cloned.  For example, running `mkdocs serve` looks for `docs/generated/inventree_settings.json`, which doesn't exist in a new repo.  

I had a look around, and it seems `inventree_settings.json` is created by `invoke int.export-settings-definitions`, but at this stage, invoke isn't installed.  Invoke is easy enough to install, but when I run it, it needs Django, and suddenly we need a whole lot more than the instructions in `README.md`.  

Another minor issue: The bare metal instructions do a clone into a `src` directory, but the clone here doesn't.  That could cause confusion for someone who wants to work on documentation in an existing checkout)

Another minor issue: I ran `invoke int.export-settings-definitions` in a working install, and it generated `inventree_settings.json` at the top level of the checkout.  I copied this into my fresh clone, but `mkdocs serve` can't find it, because it's looking in `docs/generated/inventree_settings.json`.  So even if we instruct the user to run `invoke int.export-settings-definitions`, there still needs to be some connect-the-dots so that `mkdocs serve` finds it.

Do the instructions as currently written work for you?  If so, what am I missing / doing wrong?   If not, how do we improve `README.md` so people can follow them and get a useful result?  Is it easier just to require people to have a working InvenTree installation before running mkdocs?  If so, should we amend the instructions to say this?

**Comment by CapnKernel** [comment]
Further to the above, if I fudge things to provide `docs/generated/inventree_settings.json`, mkdocs then complains about missing `docs/generated/inventree_tags.yml`.  So I look in `tasks.py`, and it seems likely that I need to run `invoke int.export-definitions`, which will generate `inventree_settings.json` and `inventree_tags.yml`.  However when I run `invoke int.export-definitions`, I get this:
```
(env) inventree@host:~/src$ invoke int.export-definitions
Unknown environment, not checking used invoke command
Exporting definitions...
Exporting settings definition to '/home/inventree/src/generated/inventree_settings.json'...
Python version 3.12.3 - /home/inventree/env/bin/python3
Traceback (most recent call last):
  File "/home/inventree/src/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
...
  File "/home/inventree/src/src/backend/InvenTree/InvenTree/management/commands/export_settings_definitions.py", line 50, in handle
    with open(filename, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/inventree/src/generated/inventree_settings.json'
ERROR: InvenTree command failed: 'python3 manage.py export_settings_definitions /home/inventree/src/generated/inventree_settings.json'
- Refer to the error messages in the log above for more information
(env) inventree@host:~/src$ 
```

I note here that `docs/generated/inventree_settings.json` ≠  `src/generated/inventree_settings.json`, and I'm all out of ideas on what to try next.

**Comment by matmair** [comment]
You will need something like these commands for environment setup (also see readthedocs.yml)
```
pip install -U invoke
pip install -r docs/requirements.txt
pip install -r src/backend/requirements.txt
invoke migrate
```
And this command to build the docs `invoke build-docs`

**Comment by SchrodingersGat** [comment]
@CapnKernel also you'll need to run `invoke build-docs` step first - I've updated the docs around building the docs - https://github.com/inventree/InvenTree/pull/10998

**Comment by SchrodingersGat** [comment]
closed in #10998

**Comment by CapnKernel** [comment]
Thank you @SchrodingersGat and @matmair  for your comments.

This is not fixed.  This is nowhere near fixed.  Was it tested?  Am I missing something here?

The title of this issue is "mkdocs instructions don't work as written".  The important thing here is __as written__.  That's still the case, even with the changes two days ago.  Let's try them out:

```
[mjd@xiaomao git]$ python --version
Python 3.13.9
[mjd@xiaomao git]$ git clone https://github.com/inventree/inventree
Cloning into 'inventree'...
remote: Enumerating objects: 203274, done.
remote: Counting objects: 100% (694/694), done.
remote: Compressing objects: 100% (335/335), done.
remote: Total 203274 (delta 551), reused 365 (delta 359), pack-reused 202580 (from 4)
Receiving objects: 100% (203274/203274), 284.44 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (129096/129096), done.
[mjd@xiaomao git]$ pip install --require-hashes -r docs/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'
[mjd@xiaomao git]$ 
```

The error is hardly surprising.  The instructions __as written__ would at least need a `cd` into the clone subdir.  So let's _pretend_ there's a `cd` in the instructions:

```
[mjd@xiaomao git]$ cd inventree
[mjd@xiaomao inventree]$ pip install --require-hashes -r docs/requirements.txt
Collecting anyio==4.10.0 (from -r docs/requirements.txt (line 3))
  Using cached anyio-4.10.0-py3-none-any.whl (107 kB)
Requirement already satisfied: babel==2.17.0 in /usr/lib/python3.13/site-packages (from -r docs/requirements.txt (line 7)) (2.17.0)
...
  Using cached wcmatch-10.1-py3-none-any.whl (39 kB)
Installing collected packages: paginate, hjson, essentials, watchdog, urllib3, typing-extensions, termcolor, super-collections, sniffio, smmap, six, setuptools, pyyaml, pygments, platformdirs, pathspec, packaging, mkdocs-material-extensions, mergedeep, markupsafe, markdown, idna, h11, editorconfig, colorama, click, charset-normalizer, certifi, bracex, backrefs, wcmatch, rich, requests, pyyaml-env-tag, python-dateutil, pymdown-extensions, mkdocs-get-deps, jsbeautifier, httpcore, griffe, gitdb, essentials-openapi, beautifulsoup4, anyio, httpx, gitpython, ghp-import, mkdocs, neoteroi-mkdocs, mkdocs-simple-hooks, mkdocs-redirects, mkdocs-mermaid2-plugin, mkdocs-material, mkdocs-macros-plugin, mkdocs-include-markdown-plugin, mkdocs-git-revision-date-localized-plugin, mkdocs-autorefs, mkdocstrings, mkdocstrings-python
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/lib/python3.13'
Consider using the `--user` option or check the permissions.

[mjd@xiaomao inventree]$ 
```

This error also isn't surprising, because there's no local virtual environment, and most importantly, the instructions __as written__ don't say to use one.  So let's _pretend_ there are instructions to make and use one:

(I want to point out that starting the instructions with `git clone` implies that we're _not_ re-using an existing InvenTree virtual env here)

```
[mjd@xiaomao inventree]$ python -m venv env
[mjd@xiaomao inventree]$ . env/bin/activate
(env) [mjd@xiaomao inventree]$ pip install --require-hashes -r docs/requirements.txt
Collecting anyio==4.10.0 (from -r docs/requirements.txt (line 3))
  Using cached anyio-4.10.0-py3-none-any.whl (107 kB)
Collecting babel==2.17.0 (from -r docs/requirements.txt (line 7))
  Using cached babel-2.17.0-py3-none-any.whl (10.2 MB)
Collecting backrefs==5.9 (from -r docs/requirements.txt (line 13))
  Using cached backrefs-5.9-py313-none-any.whl (399 kB)
...
Collecting wcmatch==10.1 (from -r docs/requirements.txt (line 578))
  Using cached wcmatch-10.1-py3-none-any.whl (39 kB)
Installing collected packages: paginate, hjson, essentials, watchdog, urllib3, typing-extensions, termcolor, super-collections, soupsieve, sniffio, smmap, six, setuptools, pyyaml, pygments, platformdirs, pathspec, packaging, mkdocs-material-extensions, mergedeep, mdurl, markupsafe, markdown, idna, h11, editorconfig, colorama, click, charset-normalizer, certifi, bracex, backrefs, babel, wcmatch, requests, pyyaml-env-tag, python-dateutil, pymdown-extensions, mkdocs-get-deps, markdown-it-py, jsbeautifier, jinja2, httpcore, griffe, gitdb, essentials-openapi, beautifulsoup4, anyio, rich, httpx, gitpython, ghp-import, mkdocs, neoteroi-mkdocs, mkdocs-simple-hooks, mkdocs-redirects, mkdocs-mermaid2-plugin, mkdocs-material, mkdocs-macros-plugin, mkdocs-include-markdown-plugin, mkdocs-git-revision-date-localized-plugin, mkdocs-autorefs, mkdocstrings, mkdocstrings-python
Successfully installed anyio-4.10.0 babel-2.17.0 backrefs-5.9 beautifulsoup4-4.13.4 bracex-2.6 certifi-2025.8.3 charset-normalizer-3.4.2 click-8.1.8 colorama-0.4.6 editorconfig-0.17.1 essentials-1.1.6 essentials-openapi-1.3.0 ghp-import-2.1.0 gitdb-4.0.12 gitpython-3.1.45 griffe-1.11.0 h11-0.16.0 hjson-3.1.0 httpcore-1.0.9 httpx-0.28.1 idna-3.10 jinja2-3.1.6 jsbeautifier-1.15.4 markdown-3.8.2 markdown-it-py-3.0.0 markupsafe-3.0.2 mdurl-0.1.2 mergedeep-1.3.4 mkdocs-1.6.1 mkdocs-autorefs-1.4.2 mkdocs-get-deps-0.2.0 mkdocs-git-revision-date-localized-plugin-1.5.0 mkdocs-include-markdown-plugin-7.2.0 mkdocs-macros-plugin-1.5.0 mkdocs-material-9.7.0 mkdocs-material-extensions-1.3.1 mkdocs-mermaid2-plugin-1.2.3 mkdocs-redirects-1.2.2 mkdocs-simple-hooks-0.1.5 mkdocstrings-1.0.0 mkdocstrings-python-1.16.12 neoteroi-mkdocs-1.2.0 packaging-25.0 paginate-0.5.7 pathspec-0.12.1 platformdirs-4.3.8 pygments-2.19.2 pymdown-extensions-10.16.1 python-dateutil-2.9.0.post0 pyyaml-6.0.3 pyyaml-env-tag-1.1 requests-2.32.5 rich-14.1.0 setuptools-80.9.0 six-1.17.0 smmap-5.0.2 sniffio-1.3.1 soupsieve-2.7 super-collections-0.6.2 termcolor-3.1.0 typing-extensions-4.14.1 urllib3-2.6.0 watchdog-6.0.0 wcmatch-10.1

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
(env) [mjd@xiaomao inventree]$ 
```
So that works, which is good.  

The next line in the instructions is `invoke build-docs`.  Let's see how that goes.

```
(env) [mjd@xiaomao inventree]$ invoke build-docs
bash: invoke: command not found
(env) [mjd@xiaomao inventree]$ 
```

So, again, the instructions don't work __as written__.  Let's try installing invoke (which isn't in the instructions, but hey):

```
(env) [mjd@xiaomao inventree]$ pip install invoke
Collecting invoke
  Using cached invoke-2.2.1-py3-none-any.whl.metadata (3.3 kB)
Using cached invoke-2.2.1-py3-none-any.whl (160 kB)
Installing collected packages: invoke
Successfully installed invoke-2.2.1

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
(env) [mjd@xiaomao inventree]$ 
```

Ok that's good, let's retry the `invoke build-docs` from the instructions:

```
(env) [mjd@xiaomao inventree]$ invoke build-docs
Unknown environment, not checking used invoke command
Running InvenTree database migrations...
Traceback (most recent call last):
  File "/home/mjd/git/inventree/src/backend/InvenTree/manage.py", line 13, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mjd/git/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
    ~~~~^^
  File "/home/mjd/git/inventree/src/backend/InvenTree/manage.py", line 15, in main
    raise ImportError(
    ...<3 lines>...
    ) from exc
ImportError: INVE-E14: Could not import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
ERROR: InvenTree command failed: 'python3 manage.py makemigrations'
- Refer to the error messages in the log above for more information
(env) [mjd@xiaomao inventree]$ 
```

It seems that it's not sufficient to create a new virtual env,  and install invoke, nor are the packages in `docs/requirements.txt` enough to get invoke running.  It also appears that invoke can't be run without 1) using an existing virtual env that includes invoke, _and_ 2) has Django (which is not in `docs/requirements.txt`), and the "database migrations" in the error message suggests other setup is needed, such as a database.

I think the goal here is that following the instructions __as written__ produce a meaningful result.  At the moment they don't, for several reasons as demonstrated.

* So, should people be able to build the docs without a virtual env?  If so, how?  (Instructions would need to be amended to show how)
* If people need a virtual env, is it sufficient to create and populate it with the packages from `docs/requirements.txt`?  If so, how?  (Instructions would need to be amended to show how)
* If people should reuse an existing virtual env (from when InvenTree was installed), then this will work, but the instructions would need to be amended to show how.

I'm happy to amend the documentation, but I need your guidance on how this is supposed to work.

**Comment by SchrodingersGat** [comment]
@CapnKernel ok, fair points - there are a lot of assumptions which have not been laid out.

> Was it tested?

Yes. albeit from a running dev installation.

Perhaps it would be sufficient to add a foreword to `docs/README.md` with something like the following:

```
This guide assumes that you have already:


1. Setup a python virtual environment
2. Installed the `invoke` tool
3. Run `invoke update`

And that you are operating from within the InvenTree source code root directory

```

The core missing instruction here (which has been assumed to this point) is that you are building the docs from a working InvenTree dev environment - bare minimum you have installed the deps and run `invoke update`

**Comment by CapnKernel** [comment]
Noted.  Would you like me to amend the docs to say that?

**Comment by SchrodingersGat** [comment]
That would be great, thanks! And also that is for taking the time to point out the inconsistencies

**Comment by CapnKernel** [comment]
Thank you for taking my feedback constructively 😄!
