### ISSUE TITLE
PUI CORS issues only with the default part image 

### ISSUE THREAD

**Issue by wolflu05** [inventree/InvenTree#5948]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

If I open a part with an black image in PUI I have the following errors in console:
![image](https://github.com/inventree/InvenTree/assets/76838159/bcb7bdb1-413e-42e8-b392-3346b7b78253)

### Steps to Reproduce

1. Run PUI on another port than the dev server in dev mode
2. open the parts list table which renders parts without a part image
3. See errors in browser console

### Expected behaviour

no errors, `/static/img/blank_image.png` should load as the other images.

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.23
Commit Hash: 53bd75e
Commit Date: 2023-11-16
Commit Branch: pui-improvements
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.31
Installer: GIT

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
I believe this is related to how Django handles static files in particular, with the "development" server.

Ref: https://stackoverflow.com/questions/55751033/django-cors-on-static-asset

**Comment by wolflu05** [comment]
Should we then use this `--nostatic` method for development by default and setup the static handlers ourselves?

**Comment by SchrodingersGat** [comment]
@wolflu05 this *may* have been fixed now with latest CORS fixes - can you please confirm when you have a chance?

**Comment by wolflu05** [comment]
I still have the error, do I need to do something specific or just pull the newest code? (I tested with d502d933801c62ce8ecd522c8d874a9d7985db6f)

**Comment by wolflu05** [comment]
Tried now, still the same behavior. 
So to clarify, what I did:
1. run inventree server on port 8000
2. run pui via `npm run dev`
3. connect to `http://localhost:5137`, add a new server pointing to `http://localhost:8000`
4. open the parts page where a lot of parts that have no image are shown
5. See the errors in the dev console

**Comment by SchrodingersGat** [comment]
I have just retried locally, with the server pointing at both `localhost:5173` and `localhost:8000` - both seem to work on my end. Do the tables load? Just the images are not coming through?

**Comment by wolflu05** [comment]
Everything loads, just tested again with chrome (was using safari before on macos). Everything loads, except the image of parts that have no part image. Same for the demo server with a locally run frontend. Because I get a lot of these errors:
<img width="1618" alt="image" src="https://github.com/inventree/InvenTree/assets/76838159/0736e0f2-0099-42a7-990c-01932c3e70b0">

Do you also run the frontend on port 5137 and accessed it through that port and than added a new server host at localhost:8000, selected that and opened the parts list where parts are shown that have no image associated?

Is there something that I need to configure first on the inventree dev server?


And I also get a lot of these prompts that quickly close after they are shown
![image](https://github.com/inventree/InvenTree/assets/76838159/477f1494-692d-4d33-97f8-601f5b15e981)

This could be related to these rejected responses from the server that appear in the console:
<img width="1618" alt="image" src="https://github.com/inventree/InvenTree/assets/76838159/24f3819f-f2fb-40ac-97a8-de506038d385">

Here you can see that there is a `WWW-Authenticate: Basic realm="api"` header send back from the server that indicate for the browser to show such a basic login dialog:
<img width="1740" alt="image" src="https://github.com/inventree/InvenTree/assets/76838159/418ba368-6039-4600-96ff-5a2afc61cb69">

**Comment by SchrodingersGat** [comment]
Ah, ok for the static files I am also getting a CORS error still:

![image](https://github.com/inventree/InvenTree/assets/10080325/9db34383-c068-4964-a88a-c3cc572b277d)

This is separate to the issues that I have recently been looking into.

**Comment by matmair** [comment]
I think this was addressed. Can you validate if it now works on your setup @wolflu05? I'm not sure if my config or the code makes it work.

**Comment by wolflu05** [comment]
Tested with 8638f3b72045f28923edcc1f805d9ccadda2cd1e, but it's still not working, still getting these CORS issues from the initial post. Do I have to configure something special?

**Comment by matmair** [comment]
It should not need configuration, maybe my specific CORS settings for dev address it but they are insecure for deploy so we need to look into this properly.
