### ISSUE TITLE
[CI] Developer UX issues with current image

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6618]
- https://github.com/inventree/InvenTree/pull/6614 has broken docker image push
- builds are stuck on "building wheel for grpcio"
- Related issue: https://github.com/inventree/InvenTree/issues/6291

*Edit: Docker push is not broken, but it does take a significant amount of time just to build this one package*

<img width="780" alt="image" src="https://github.com/inventree/InvenTree/assets/10080325/454301e4-f06f-4a86-8033-20b9db5e3a69">

-------------

After much research, this seems to be related specifically to building the alpine image on ARM.

The [downloads page](https://pypi.org/project/grpcio/#files) shows lots of other precompiled wheel options but not the ones we want.

#### References

- https://github.com/grpc/grpc/issues/27940
- https://github.com/grpc/grpc/issues/34998
- https://github.com/grpc/grpc/issues/32044
- https://github.com/grpc/grpc/issues/27512
- https://github.com/grpc/grpc/issues/27512
- https://github.com/home-assistant/core/issues/56669
- https://github.com/home-assistant/core/issues/56669
- https://github.com/home-assistant/core/issues/40148

#### A) Use pre-build grpcio library

Alpine ships the [py3-grpcio](https://pkgs.alpinelinux.org/package/edge/community/riscv64/py3-grpcio) package which comes with the `1.54.2`  version of the library pre-installed. This may sidestep our need to build the library entirely.

#### B) Different Base Image

Alpine / musl is a big part of the "problem" here - using a different base image would make this a much more tractable problem.

#### C) Compile Wheel

Can we compile a wheel for grpcio ourselves for the aarch64 architecture?

#### D) Consider Default Support for grpcio

Currently we use this for tracing. I do not want to split up dependencies, this is not my ideal solution. But including it here as a point of consideration.

**Comment by SchrodingersGat** [comment]
@matmair @wolflu05 this single library (`grpcio`) is the cause for our very long docker build times on GitHub Actions.

**Comment by matmair** [comment]
This was the main reason I implemented the matrix build as it seems there are problems with that solution I think c) would be the next best

**Comment by wolflu05** [comment]
I think for a optimal setup, we need to:
1. use matrix builds and merge the manifest so that we don't have the issue we recently had. See https://docs.docker.com/build/ci/github-actions/multi-platform/
2. build our own wheel and cache that
3. use the free m1 runners for arm building

**Comment by matmair** [comment]
regarding 3. - I tried to get docker running on mac and it seems to be difficult. To get the M1 runner we should run MacOS 14 which seems to have problems with colima.

Also see https://github.com/actions/runner-images/issues/17

**Comment by matmair** [comment]
Arm runners + docker seems to be a problem https://github.com/douglascamata/setup-docker-macos-action?tab=readme-ov-file#arm64-processors-m1-m2-m3-series-used-on-macos-14-images-are-unsupported; which kind of defeats the purpose

**Comment by SchrodingersGat** [comment]
I think compiling and caching our own wheel would go most of the way and certainly be a drastic improvement to our build times. That should be our priority

**Comment by SchrodingersGat** [comment]
Anyone have experience doing something like this in GitHub?

**Comment by wolflu05** [comment]
Ok, thanks for referencing these. I now understand the trouble you mean. Very said that there are no Linux arm runners for free available.

**Comment by matmair** [comment]
> I think compiling and caching our own wheel would go most of the way and certainly be a drastic improvement to our build times. That should be our priority

Looking into it. Seems simpler than getting docker to run

**Comment by matmair** [comment]
Maybe we can use piwheels too - they are already building wheels https://www.piwheels.org/project/grpcio/

**Comment by SchrodingersGat** [comment]
@matmair isn't that for armv7 only?

**Comment by matmair** [comment]
@SchrodingersGat I think this was thourougly solved by https://github.com/inventree/InvenTree/pull/8680 - can we close this?

**Comment by SchrodingersGat** [comment]
This was *partially* solved. The following issues remain:

1. Cannot build the devcontainer (or docker image in general) on Apple M1 (hangs on grpcio)
2. Cannot run playwright tests in the devcontainer (Alpine incompatibility)

**Comment by SchrodingersGat** [comment]
This can be closed now:

- upstream for grpcio now compiles in a reasonable amount of time
- the devcontainer image uses debian now
