### ISSUE TITLE
make: *** [migrate] Error 1

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#743]
I did a pull this morning and got the following error.  Now InvenTree will not start.

django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.contrib.admin.templatetags.admin_static': cannot import name 'RemovedInDjango30Warning'
Makefile:14: recipe for target 'migrate' failed
make: *** [migrate] Error 1

**Comment by SchrodingersGat** [comment]
Hi @lookme2 did you run `make update` or `make migrate`? Are you running in a virtual environment and all the required PIP packages are up to date?
I have not seen this error on my setup, it feels like it may be caused by a package incompatibility...

**Comment by SchrodingersGat** [comment]
Also can you provide the full error output?

**Comment by lookme2** [comment]
@SchrodingersGat I am running it in a VM with Ubuntu 18.04.  I did to a make update and a make migrate both.  I messed around with it yesterday afternoon and managed to get it running.  To be honest I'm not sure how I fixed it.  

If there is some log file you would like to see let me know.  I'll be more than happy to supply that for you.

**Comment by SchrodingersGat** [comment]
That is weird. Perhaps there was a step you missed the first time around? Thanks for letting my know you got it fixed.
