### ISSUE TITLE
[Bug] Template Editor Caching Issue

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8259]
When editing a template file in the "template editor" interface (in PUI), the template data is fetched from the file (on the server), from the raw file URL e.g. `/media/report/label/part_label.html`

*However* the server can cache this file, meaning that the file returned may not be the correct "up to date" file, if the template has been very recently edited.

This can lead to potential issues if the template editor is opened / closed rapidly, and overwriting the upstream file with an out-of-date cached copy.

### References

- https://github.com/inventree/inventree/issues/9398

**Comment by matmair** [comment]
@SchrodingersGat is this related to PUI or the underlying report generation?

**Comment by SchrodingersGat** [comment]
This is not related to the UI it is based on caching of uploaded files by the backend

**Comment by SchrodingersGat** [comment]
This would be *properly* solved by storing the templates in the database, and not as file objects. We should look into this.

As a "patch" - we could use a "no-cache" header when requesting the template files - which should prevent the proxy server from returning the cached copy.

@wolflu05 @matmair thoughts? In particular @wolflu05 as you wrote most of the template editor code

**Comment by wolflu05** [comment]
Not sure, in the end storing them in the database might be the best solution. Also we need to think about how we handle snippets and assets.

But for now a no cache header might be suitable.

**Comment by NerosKi** [comment]
I believe since V1.0.0 this issue is back. It does save it in the file but the template editor cashed version does not update I think.

**Comment by SchrodingersGat** [comment]
@NerosKi please open a new issue, include screenshots, error messages, etc
